bug: Cannot toggle including_default_value_fields in to_dict method. #231
googleapis/proto-plus-python pull request #232
Opened 2021-06-07 14:12 UTC by vishwaja13

Solution to the following issue#231, should work as boolean value and according to the value the GoogleAdsRow default columns should or should not return in results.

If including_default_value_fields  is ```False``` default columns should not return and if ```True``` default values should return now.

2021-06-07 14:18 UTC, vishwaja13 commented
@googlebot I signed it!

2021-06-07 14:23 UTC, vishwaja13 commented
> @googlebot I fixed it.

2021-06-07 14:28 UTC, vishwaja13 commented
@googlebot I fixed it.

2021-06-07 15:51 UTC, busunkim96 commented
Hi! Thanks for the PR.

It looks like CLA bot expects your commits to be associated with an @gmail account but the commit has `Vishwaja@Vishwajas-MacBook-Air.local` instead. Could you edit your commit please? (see [stackoverflow post](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) for help doing this).

2021-06-07 15:57 UTC, tseaver requested changes
Thanks very much for the patch!  In addition to the tweaks requested inline, this PR needs to add a test (in `tests/test_message.py`) to ensure that the `including_default_value_fields` value is passed correctly.

2021-06-07 15:57 UTC, tseaver commented on proto/message.py
> +        cls, instance, *, use_integers_for_enums=True, preserving_proto_field_name=True, including_default_value_fields=True,
Please wrap:
```suggestion
        cls,
        instance,
        *,
        use_integers_for_enums=True,
        preserving_proto_field_name=True,
        including_default_value_fields=True,
```

Also, please add `including_default_value_fields` to the docstring below.

2021-06-07 18:49 UTC, software-dov requested changes

2021-06-07 18:49 UTC, software-dov commented on proto/message.py
> +        including_default_value_fields=True,
The default for `MessageToDict` is `False`, and implicitly changing it here could constitute a breaking change. I'm okay with adding this option, but I think we should keep the default False.

2021-06-07 18:50 UTC, software-dov approved these changes

2021-06-07 19:32 UTC, tseaver commented on proto/message.py
> +            including_default_value_fields (Optional(bool)): An option that determines whether the default field values should be included in the results. Default is True.
Please wrap here as well:
```suggestion
            including_default_value_fields (Optional(bool)): An option that
            determines whether the default field values should be included in
            the results. Default is True.
```

2021-06-07 19:33 UTC, tseaver requested changes

2021-06-07 19:33 UTC, tseaver commented on tests/test_message.py
> +test_serialize_to_dict()
Please remove the test invocation here.

2021-06-07 19:34 UTC, tseaver commented on tests/test_message.py
> +test_serialize_to_dict()
```suggestion
```

2021-06-07 19:57 UTC, vishwaja13 commented
> @googlebot I fixed it.

2021-06-09 13:50 UTC, vishwaja13 commented
@googlebot I fixed it.

2021-06-09 16:04 UTC, tseaver approved these changes

2021-06-25 14:27 UTC, vishwaja13 commented
cla process completed.

2021-06-25 14:53 UTC, vishwaja13 commented
workflow style-check fixes in tests/test_message.py

2021-06-29 16:38 UTC, merged